import { type ClientSchema, a, defineData } from "@aws-amplify/backend";
import { postConfirmation } from '../functions/post-confirmation/resource';

const schema = a.schema({

  // ─────────────────────────────────────────────────────────────
  // USER PROFILE
  // Created automatically via postConfirmation Lambda.
  // Owner can read/update their own. Admins have full access.
  // ─────────────────────────────────────────────────────────────
  UserProfile: a.model({
    userId:           a.string().required(),  // matches Cognito sub
    email:            a.string().required(),
    givenName:        a.string(),
    familyName:       a.string(),
    phoneNumber:      a.string(),
    companyName:      a.string(),
    jobTitle:         a.string(),
    addressLine1:     a.string(),
    city:             a.string(),
    state:            a.string(),
    zipCode:          a.string(),
    country:          a.string(),
    subscriptionType: a.string().default("free"), // "free" | "paid"
    profileCompleted: a.boolean().default(false),
    // NOTE: createdAt/updatedAt auto-generated by Amplify — do not add them
  })
  .secondaryIndexes((index) => [
    index("userId"),  // look up profile by Cognito userId
  ])
  .authorization((allow) => [
    allow.ownerDefinedIn("userId").to(["create", "read", "update", "delete"]),
    allow.groups(["ADMINS"]).to(["create", "read", "update", "delete"]),
  ]),


  // ─────────────────────────────────────────────────────────────
  // PAGE
  // One record per topic and subtopic.
  // Admin edits intro via TipTap rich text editor.
  //
  // Slug naming convention:
  //   "home"                    → / (home page)
  //   "news"                    → /news
  //   "news-opc"                → /news/opc
  //   "news-markets"                        → /news/markets (subcat1)
  //   "news-markets-feature-of-the-week"    → /news/markets/feature-of-the-week (subcat2)
  //   "news-shale"                          → /news/shale (subcat1)
  //   "news-shale-[subcat2]"                → /news/shale/[subcat2] 
  //   "videos"                  → /videos
  //   "videos-presentations"    → /videos/presentations
  //   "videos-markets"          → /videos/markets
  //   "whitepapers"             → /whitepapers
  //   "whitepapers-[subtopic]"  → /whitepapers/[subtopic]
  //   "resources"               → /resources
  //   "events"                  → /events
  
  // ─────────────────────────────────────────────────────────────
  Page: a.model({
    slug:     a.string().required(), // unique — see convention above
    title:    a.string().required(), // displayed as page heading
    intro:    a.string(),            // TipTap HTML — intro paragraph(s) above listing
    status:   a.enum(["draft", "published"]),
    seo:      a.json(),              // { metaTitle, metaDescription, keywords }
    featured: a.boolean().default(false),
    authorId: a.string(),
    // NOTE: createdAt/updatedAt auto-generated by Amplify — do not add them
    // NOTE: sections removed — no code stored in DB
  })
  .secondaryIndexes((index) => [
    index("slug"),  // fetch page intro by slug in one query
  ])
  .authorization((allow) => [
    allow.guest().to(["read"]),
    allow.authenticated().to(["read"]),
    allow.groups(["ADMINS"]).to(["create", "read", "update", "delete"]),
  ]),


  // ─────────────────────────────────────────────────────────────
  // CONTENT
  // One table for ALL content types:
  //   news, videos, whitepapers, resources, events
  //
  // topic field drives which section it belongs to:
  //   "news"         → /news and /news/[subtopic]
  //   "videos"       → /videos and /videos/[subtopic]
  //   "whitepapers"  → /whitepapers and /whitepapers/[subtopic]
  //   "resources"    → /resources  
  //   "events"       → /events  
  //
  // Listing pages show: title + date + extractFirstParagraph(body)
  // Detail pages show:  full TipTap HTML body + type-specific extras
  //
  // isPublic controls access:
  //   true  = anyone can view (no login required)
  //   false = must be logged in to view
  // ─────────────────────────────────────────────────────────────
  Content: a.model({
    // ── Core fields (all types) ──────────────────────────────
    title:       a.string().required(),
    slug:        a.string().required(),  // e.g. "crude-markets-june-2026"
    body:        a.string(),             // TipTap HTML — full content
    topic:       a.string().required(),  // "news" | "videos" | "whitepapers" | "resources" | "events"
    subcat1:    a.string(),             // e.g. "markets", "shale", "opc", "presentations"
    subcat2:    a.string(),            
    date:        a.date().required(),    // YYYY-MM-DD — used for sorting
    isPublished: a.boolean().default(true),
    isPublic:    a.boolean().default(false), // false = login required to view
    authorId:    a.string(),
    seo:         a.json(),               // { metaTitle, metaDescription, keywords }

    // ── Video specific ───────────────────────────────────────
    s3Key:       a.string(),             // "videos/modcon-cdu.mp4" — signed URL generated at runtime
    
    // ── Whitepaper / Resource specific ──────────────────────
    fileKey:     a.string(),             // "whitepapers/report-2026.pdf" — S3 key for download

    // ── Event specific ───────────────────────────────────────
    location:        a.string(),         // physical or virtual location
    eventDate:       a.datetime(),       // full datetime for events (date field = day only)
    maxAttendees:    a.integer(),
    registrationUrl: a.string(),         // external registration link

    // ── Media ────────────────────────────────────────────────
    imageUrl:    a.string(),             // optional hero/thumbnail image
  })
  .secondaryIndexes((index) => [
    index("slug"),                        // fetch single item by slug
    index("topic").sortKeys(["date"]),    // list all items for a topic sorted by date
    index("subcat1").sortKeys(["date"]), // list items by subcat1 sorted by date
    index("subcat2").sortKeys(["date"]), // list items by subcat2 sorted by date
  ])
  .authorization((allow) => [
    allow.guest().to(["read"]),           // guests see public content metadata
    allow.authenticated().to(["read"]),   // logged-in users see protected content
    allow.groups(["ADMINS"]).to(["create", "read", "update", "delete"]),
  ]),

})
.authorization((allow) => [
  allow.resource(postConfirmation).to(["mutate"]),
]);

export type Schema = ClientSchema<typeof schema>;

export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: "userPool",
    apiKeyAuthorizationMode: {
      expiresInDays: 30,
    },
  },
});
