import { type ClientSchema, a, defineData } from "@aws-amplify/backend";
import { postConfirmation } from '../functions/post-confirmation/resource';

const schema = a.schema({

  // ─────────────────────────────────────────────────────────────
  // USER PROFILE
  // Created automatically via postConfirmation Lambda.
  // Owner can read/update their own. Admins have full access.
  // ─────────────────────────────────────────────────────────────
  UserProfile: a.model({
    userId:           a.string().required(),  // matches Cognito sub
    email:            a.string().required(),
    givenName:        a.string(),
    familyName:       a.string(),
    phoneNumber:      a.string(),
    companyName:      a.string(),
    jobTitle:         a.string(),
    addressLine1:     a.string(),
    city:             a.string(),
    state:            a.string(),
    zipCode:          a.string(),
    country:          a.string(),
    subscriptionType: a.string().default("free"), // "free" | "paid"
    profileCompleted: a.boolean().default(false),
    // NOTE: createdAt/updatedAt auto-generated by Amplify — do not add them
  })
  .secondaryIndexes((index) => [
    index("userId"),  // look up profile by Cognito userId
  ])
  .authorization((allow) => [
    allow.ownerDefinedIn("userId").to(["create", "read", "update", "delete"]),
    allow.groups(["ADMINS"]).to(["create", "read", "update", "delete"]),
  ]),
  
  // One record per topic and subtopic.
  // Admin edits intro via TipTap rich text editor.
  //
  // Slug naming convention:
  //   "home"                    → / (home page)
  //   "news"                    → /news
  //   "news-opc"                → /news/opc
  //   "news-markets"                        → /news/markets (subcat1)
  //   "news-markets-feature-of-the-week"    → /news/markets/feature-of-the-week (subcat2)
  //   "news-shale"                          → /news/shale (subcat1)
  //   "news-shale-[subcat2]"                → /news/shale/[subcat2] 
  //   "videos"                  → /videos
  //   "videos-presentations"    → /videos/presentations
  //   "videos-markets"          → /videos/markets
  //   "whitepapers"             → /whitepapers
  //   "whitepapers-[subtopic]"  → /whitepapers/[subtopic]
  //   "resources"               → /resources
  //   "events"                  → /events
  
  // ─────────────────────────────────────────────────────────────
  
  Page: a.model({
    slug:     a.string().required(),
    title:    a.string().required(),
    intro:    a.string(),
    status:   a.enum(["draft", "published"]),
    seo:      a.json(),
    featured: a.boolean().default(false),
    authorId: a.string(),
  })
  .identifier(["slug"])
  .authorization((allow) => [
    allow.publicApiKey().to(["read"]),
    allow.guest().to(["read"]),
    allow.authenticated().to(["read"]),
    allow.groups(["ADMINS"]).to(["create", "read", "update", "delete"]),
  ]),

  // ─────────────────────────────────────────────────────────────
  // PAGE
  

  // ─────────────────────────────────────────────────────────────
  // CONTENT
  // One table for ALL content types:
  //   news, videos, whitepapers, resources, events
  //
  // topic field drives which section it belongs to:
  //   "news"         → /news and /news/[subtopic]
  //   "videos"       → /videos and /videos/[subtopic]
  //   "whitepapers"  → /whitepapers and /whitepapers/[subtopic]
  //   "resources"    → /resources  
  //   "events"       → /events  
  //
  // Listing pages show: title + date + extractFirstParagraph(body)
  // Detail pages show:  full TipTap HTML body + type-specific extras
  //
  // isPublic controls access:
  //   true  = anyone can view (no login required)
  //   false = must be logged in to view
  // ─────────────────────────────────────────────────────────────

const ContentMeta = a
  .model({
    title:           a.string().required(),
    slug:            a.string().required(),
    intro:           a.string(),           // PUBLIC teaser paragraph
    topic:           a.string().required(),
    subcat1:         a.string(),
    subcat2:         a.string(),
    date:            a.date().required(),
    isPublished:     a.boolean().default(true),
    isPublic:        a.boolean().default(false),
    authorId:        a.string(),
    imageUrl:        a.string(),
    seo:             a.string(),           // raw JSON string (validated on save)
    // event-specific metadata (public)
    location:        a.string(),
    eventDate:       a.datetime(),
    maxAttendees:    a.integer(),
    registrationUrl: a.string(),
  })
  .secondaryIndexes((index) => [
    index("slug"),
    index("topic").sortKeys(["date"]),
    index("subcat1").sortKeys(["date"]),
    index("subcat2").sortKeys(["date"]),
  ])
  .authorization((allow) => [
    allow.publicApiKey().to(["read", "list"]),
    allow.guest().to(["read", "list"]),
    allow.authenticated().to(["read", "list"]),
    allow.groups(["ADMINS"]).to(["create", "read", "update", "delete"]),
  ]);

const ContentBody = a
  .model({
    metaId:  a.id().required(),   // FK → ContentMeta.id
    body:    a.string(),          // full article HTML (protected)
    s3Key:   a.string(),          // video S3 key
    fileKey: a.string(),          // whitepaper / resource S3 key
  })
  .authorization((allow) => [
    allow.authenticated().to(["read", "list"]),
    allow.groups(["ADMINS"]).to(["create", "read", "update", "delete"]),
  ]);


  // ─────────────────────────────────────────────────────────────
  

export type Schema = ClientSchema<typeof schema>;

export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: "userPool",
    apiKeyAuthorizationMode: {
      expiresInDays: 30,
    },
  },
});
