import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./app.css";
import "./globals.css";

import Header from "./components/Header";
import Footer from "./components/Footer";
import AmplifyInit from './AmplifyInit';
import '@aws-amplify/ui-react/styles.css';
import { Authenticator } from '@aws-amplify/ui-react'; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <body>
          <AmplifyInit />
          <Authenticator.Provider>
             <Header />
             <main  >{children}</main>
             <Footer />
          </Authenticator.Provider>
      </body>
    </html>
  );
}
